# Generated by Django 4.2.8 on 2023-12-20 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission_level', models.CharField(max_length=32, verbose_name='权限')),
            ],
        ),
        migrations.AddField(
            model_name='admin',
            name='Admin_level',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='app01.permissions', verbose_name='管理员权限'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='User_level',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='app01.permissions', verbose_name='员工权限'),
        ),
    ]
